<a href="https://colab.research.google.com/github/rinato/ai_project/blob/master/appendix2_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 라이브러리 import

import tensorflow as tf
import pandas as pd

In [2]:
# 보스톤 집값 예측
# 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)
보스턴.head()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [3]:
# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [8]:
# 모델을 만듭니다.
# hidden layer 추가

X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [12]:
# 모델을 만듭니다.
# hidden layer 추가
# appendix2-model

X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [13]:
# 모델을 학습합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 17.4171
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 14.0034
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 14.8275
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 16.2817
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 16.0152
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 15.6083
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 15.2465
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 19.3911
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 15.3880
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 13.7342


In [14]:
# 모델을 이용합니다.
print(model.predict(독립[:5]))
print(종속[:5])

[[28.742771]
 [24.174694]
 [31.844389]
 [31.094946]
 [30.38681 ]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [15]:
# 아이리스 품종 분류
#1. 과거데이터를 준비.
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(path)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [16]:
encodi = pd.get_dummies(iris)
encodi.head()
print(encodi.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [17]:
#독립변수, 종속변수
Independent = encodi[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
Dependent = encodi[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(Independent.shape, Dependent.shape)

(150, 4) (150, 3)


In [18]:
# 2. 모델의 구조를 만듭니다.
#  hidden layer 추가
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss = 'categorical_crossentropy', metrics='accuracy')

In [25]:
# 2. 모델의 구조를 만듭니다.
#  hidden layer 추가
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss = 'categorical_crossentropy', metrics='accuracy')

In [27]:
# 데이터로 모델을 학습합니다.(FIT)
model.fit(Independent, Dependent, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 3ms/step - loss: 0.2881 - accuracy: 0.9067
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 0.2901 - accuracy: 0.9000
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 0.2711 - accuracy: 0.9133
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3091 - accuracy: 0.8733
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 0.2727 - accuracy: 0.9200
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 0.2732 - accuracy: 0.9200
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3091 - accuracy: 0.8867
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 0.2702 - accuracy: 0.9067
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 0.2964 - accuracy: 0.8800
Epoch 10/100
5/5 [==============================] - 0s 3ms/step - loss: 0.3054 - accuracy: 0.8667
Epoch 11/100
5/5 [===========

In [21]:
# 4. 모델을 이용합니다.
print(model.predict(Independent[0:5]))
print(Dependent[0:5])

[[9.9962759e-01 3.6819809e-04 4.2233805e-06]
 [9.9956542e-01 4.2515469e-04 9.3834715e-06]
 [9.9920803e-01 7.8093278e-04 1.1124545e-05]
 [9.9718744e-01 2.7891234e-03 2.3448925e-05]
 [9.9935418e-01 6.4064725e-04 5.1582124e-06]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
