<a href="https://colab.research.google.com/github/rinato/ai_project/blob/master/hidden_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 라이브러리 import

import tensorflow as tf
import pandas as pd

In [4]:
# 보스톤 집값 예측
# 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)
보스턴.head()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [5]:
# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [11]:
# 모델을 만듭니다.
# hidden layer 추가

X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [12]:
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [14]:
# 모델을 학습합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 18.3944
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 17.8274
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 17.2995
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 17.0410
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 18.0284
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 17.1255
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 17.1408
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 17.0384
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 18.3098
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 17.7540


In [16]:
# 모델을 이용합니다.
print(model.predict(독립[:5]))
print(종속[:5])

[[27.315876]
 [22.954884]
 [30.648993]
 [29.240946]
 [29.477303]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [18]:
# 아이리스 품종 분류
#1. 과거데이터를 준비.
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(path)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [19]:
encodi = pd.get_dummies(iris)
encodi.head()
print(encodi.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [20]:
#독립변수, 종속변수
Independent = encodi[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
Dependent = encodi[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(Independent.shape, Dependent.shape)

(150, 4) (150, 3)


In [26]:
# 2. 모델의 구조를 만듭니다.
#  hidden layer 추가
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss = 'categorical_crossentropy', metrics='accuracy')

In [30]:
# 데이터로 모델을 학습합니다.(FIT)
model.fit(Independent, Dependent, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8183 - accuracy: 0.7333
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8043 - accuracy: 0.6933
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 0.7909 - accuracy: 0.7067
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 0.7768 - accuracy: 0.6933
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 0.7612 - accuracy: 0.6933
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 0.7484 - accuracy: 0.6933
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.7313 - accuracy: 0.7200
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 0.7153 - accuracy: 0.7533
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.6994 - accuracy: 0.7400
Epoch 10/100
5/5 [==============================] - 0s 5ms/step - loss: 0.6817 - accuracy: 0.7400
Epoch 11/100
5/5 [===========

In [31]:
# 4. 모델을 이용합니다.
print(model.predict(Independent[0:5]))
print(Dependent[0:5])

[[9.9668187e-01 3.3147514e-03 3.3811716e-06]
 [9.9605429e-01 3.9408705e-03 4.9119981e-06]
 [9.9551433e-01 4.4787270e-03 6.8793338e-06]
 [9.9415755e-01 5.8323629e-03 1.0090772e-05]
 [9.9635798e-01 3.6378966e-03 4.1279732e-06]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
